### PR TITLE
Add profile feature steamworks

### LINKED ISSUE #2: Feature: Open steam profile
Possibility to implement an open profile option based on the steam id.

I believe this to be a great option for this tool.

If any further information is required, please advise.

### PR DESCRIPTION
**Pull request by Ambushfall**

### CODE REVIEW

**Comment by Ambushfall** [comment]
Add Profile button visible in the lethal Admin panel to allow the host to add players as friends or ease future connectivity.

Apologies to the maintainer for visual studio messing with the deletions and additions. (CRLF to LF issues)

I will thoroughly test this, albeit for the time being seems to work just fine.

**Comment by gamendegamer321** [comment]
I don't really see a reason for adding this as it's already part of the base game. You can open someones profile by pressing the button next to their name in the pause menu (circled in red in the image), and as far as I know this still works with mods like BiggerLobby.

image

**Comment by Ambushfall** [comment]
> I don't really see a reason for adding this as it's already part of the base game. You can open someones profile by pressing the button next to their name in the pause menu (circled in red in the image), and as far as I know this still works with mods like BiggerLobby.
> 
> image

Unfortunately neither BiggerLobby nor MoreCompany have a working profile button.

Bigger lobby works, however messes up the index of the player, while MoreCompany entirely disables the feature.

From my perspective, an admin tool, once encountering a cheater should be able to locate his steam profile, and report aforementioned person.

Whether or not this is something you would like to include, is entirely up to you.

**Comment by gamendegamer321** [comment]
Ah I thought it did work, but seeing as it doesn't this would actually be something that's nice to have

**Review by gamendegamer321 — APPROVED** [review]

**Pull request merged**
